### ISSUE TITLE
Cannot read the response

### ISSUE THREAD

**Issue by sandaemc** [docker-php/docker-php#164]
I'm on Mac OS X El Capitan and I'm stuck with this problem:

```
PHP Fatal error:  Uncaught Http\Client\Exception\NetworkException: Cannot read the response in /Users/smacalalag/Code/project/vendor/php-http/socket-client/src/ResponseReader.php:56
Stack trace:
```

My code:

```
$docker = $container->get('docker');

$containerManager = $docker->getContainerManager();

die(print_r($containerManager->findAll()));
```

Here is my docker client config in Symfony:

```
    docker_client:
        class: Docker\DockerClient
        arguments:
            - remote_socket: "%docker_host%" # tcp://192.168.99.100:2376'
            - ssl:                    true
```

Can someone please help and point me in the right direction. The exception doesn't explain much.

Thanks!

P.S.

I tried this on my machine and it worked.

```
wget --no-check-certificate --certificate=$DOCKER_CERT_PATH/cert.pem \
     --private-key=$DOCKER_CERT_PATH/key.pem \
     https://YOUR_VM_IP:2376/images/json -O - -q
```

**Comment by sandaemc** [comment]
Okay, I think I am getting there but this just return an empty array.

```
$client = new Docker\DockerClient([
    'remote_socket' => 'tcp://192.168.99.100:2376',
    'ssl' => true,
    'stream_context_options' => [
        'ssl' => [
            'cafile' => '/Users/smacalalag/.docker/machine/machines/default/ca.pem',
            'local_cert' => '/Users/smacalalag/.docker/machine/machines/default/cert.pem',
            'local_pk' => '/Users/smacalalag/.docker/machine/machines/default/key.pem',
        ]
    ]
]);
```

**Comment by joelwurtz** [comment]
Try to use the following config

```
docker_client:
        class: Docker\DockerClient
        arguments:
            - 
                remote_socket: "%docker_host%" # tcp://192.168.99.100:2376'
                ssl:    true
                stream_context_options:
                    ssl:
                        cafile: %DOCKER_CERT_PATH%/ca.pem
                        local_cert: %DOCKER_CERT_PATH%/cert.pem
                        local_pk: %DOCKER_CERT_PATH%/key.pem
                        peer_name: boot2docker
```

Where DOCKER_CERT_PATH is the directory
