### ISSUE TITLE
Symfony bridge

### ISSUE THREAD

**Issue by Soullivaneuh** [docker-php/docker-php#255]
It would be a great addition to propose a Symfony integration bridge as a bundle.

Would you accept it here? I could work on it.

Otherwise, I'll create an external bundle.

**Comment by joelwurtz** [comment]
Sorry for late answer, goal is to provide here a symfony integration by using the `PluginClientFactory` from php-http

**Comment by Soullivaneuh** [comment]
Yes. But I think we should require [`php-http/httplug-bundle`](https://packagist.org/packages/php-http/httplug-bundle) in this case, and some adjustment might be done to make it easier.

I currently have an implementation. but it's quite tricky:

```
services:
  httplug.factory.docker:
    class: AppBundle\Httplug\ClientFactory\CallableClientFactory
    arguments:
      $factory: [ Docker\DockerClient, 'createFromEnv' ]
  Docker\Docker:
    arguments:
      $httpClient: '@httplug.client.docker'
```

Config:

```
httplug:
  plugins:
    logger: ~
  clients:
    default:
      factory: 'httplug.factory.guzzle6'
      plugins: ['httplug.plugin.logger']
    docker:
      factory: 'httplug.factory.docker'
      plugins: ['httplug.plugin.logger']
  profiling:
    captured_body_length: 1000
```

See also https://github.com/php-http/HttplugBundle/issues/210.

**Comment by joelwurtz** [comment]
Would prefer to have a suggest for the bundle with the integration directly in this lib, so not required to use docker-php but suggested when using in cujunction with symfony

**Comment by Soullivaneuh** [comment]
@joelwurtz It would obviously be a suggestion as this library is not a bundle.

It's the concept of a bridge. ;-)

Example: https://github.com/Soullivaneuh/IsoCodesValidator/tree/fc143a075c2b379dd1bf6147d2848071cabccff8/src/Bridge

**Comment by joelwurtz** [comment]
https://github.com/docker-php/docker-php/pull/261/commits/ffadd28647cebae2d9607ff5a2c556a04258e9c2

I believe this is enough for the next version of httplug bundle

**Comment by Soullivaneuh** [comment]
Maybe, have to try. :wink:

**Comment by Soullivaneuh** [comment]
@joelwurtz I don't really see how this commit will make things simpler, could you please elaborate?

At the end, I still have to call `DockerClient::createFromEnv` manually or on the services, but how can I manage it from the bundle configuration? Assuming this:

```
httplug:
  plugins:
    logger: ~
  clients:
    default:
      factory: 'httplug.factory.guzzle6'
      plugins: ['httplug.plugin.logger']
  profiling:
    captured_body_length: 1000
```

How can I manage to add, for example, the logger plugin?

AFAIK, the logic should be reversed and the socket client be called as a service from here. This is why I was talking about a bridge.

A I wrong?

**Comment by Soullivaneuh** [comment]
I finish to end up with this:

```yaml
services:
  Docker\DockerClient:
    factory: [ Docker\DockerClient, 'createFromEnv', [ '@httplug.factory.socket' ] ]
  Docker\Docker:
    factory: [ Docker\Docker, 'create', [ '@Docker\DockerClient' ] ]
```

And I indeed got a profiling and logging.

Is it what you was thinking about?

**Comment by Soullivaneuh** [comment]
Another weird thing: The `Docker\Docker::create` method takes the version as first argument. But the previous service configuration works... plus, I tried to pass a specific version to test:

```
  Docker\Docker:
    factory: [ Docker\Docker, 'create', [ !php/const:Docker\Docker::VERSION_1_31, '@Docker\DockerClient' ] ]
```
But the version is stuck at `1.32`.

**Comment by Soullivaneuh** [comment]
Ok so just forgot the two past comments, the configuration was wrong.

Fun facts: If i do:

```yaml
services:
  Docker\DockerClient:
    factory: [ Docker\DockerClient, 'createFromEnv', [ '@httplug.factory.socket' ] ]
  Docker\Docker:
    factory: [ Docker\Docker, 'create' ]
    arguments:
      $version: !php/const:Docker\Docker::VERSION_1_32
      $httpClient: '@Docker\DockerClient'
```

It works, but with 0 log.

If I remove the built http-client:

```yaml
services:
  Docker\Docker:
    factory: [ Docker\Docker, 'create' ]
    arguments:
      $version: !php/const:Docker\Docker::VERSION_1_32
```

I got this exception:

```
19:09:23 ERROR     [app] Error: "cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)" when emitting request: "POST /v1.32/containers/create 1.1" ["request" => GuzzleHttp\Psr7\Request { …},"exception" => Http\Client\Exception\RequestException { …}] []
19:09:23 ERROR     [app] Http\Client\Exception\RequestException exception thrown during analysis #17. ["message" => "cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","code" => 0,"file" => "/code/vendor/php-http/guzzle6-adapter/src/Promise.php","line" => 135] []
```

It's seems the library factory got a curl client.

I have no more ideas at the moment. I'll wait an answer before trying to do anything else on this library. :wink:

**Comment by Soullivaneuh** [comment]
Well, last thing, this is even worst. I rolled back to my current config:

```yaml
httplug:
  plugins:
    logger: ~
  clients:
    default:
      factory: 'httplug.factory.guzzle6'
      plugins: ['httplug.plugin.logger']
    docker:
      factory: 'httplug.factory.docker'
      plugins: ['httplug.plugin.logger']
  profiling:
    captured_body_length: 1000

services:
  httplug.factory.docker:
    class: AppBundle\Httplug\ClientFactory\CallableClientFactory
    arguments:
      $factory: [ Docker\DockerClient, 'createFromEnv' ]
  Docker\Docker:
    factory: [ Docker\Docker, 'create' ]
    arguments:
      $version: !php/const:Docker\Docker::VERSION_1_32
      $httpClient: '@httplug.client.docker'
```

And this is not working anymore:

```
19:18:41 ERROR     [app] TypeError exception thrown during analysis #17. ["message" => "Argument 1 passed to Docker\DockerClient::createFromEnv() must be an instance of Http\Client\Common\PluginClientFactory or null, array given, called in /code/src/AppBundle/Httplug/ClientFactory/CallableClientFactory.php on line 34","code" => 0,"file" => "/code/vendor/docker-php/docker-php/src/DockerClient.php","line" => 64] []
```
