### ISSUE TITLE
Volumes and docker dind

### ISSUE THREAD

**Issue by Soullivaneuh** [docker-php/docker-php#256]
Sorry to open it as an issue, I can't find anything on the doc about the volumes.

I wrote this testing code:

```php
use Docker\API\Model\ContainerConfig;
use Docker\API\Model\HostConfig;
use Docker\Docker;
use Http\Client\Common\Exception\ServerErrorException;

require_once 'vendor/autoload.php';

$docker = new Docker();

$hostConfig = new HostConfig();
$hostConfig->setBinds([__DIR__.':/code-docker']);

try {
    $containerCreateResult = $docker->getContainerManager()->create(
        (new ContainerConfig())
            ->setImage('busybox:latest')
            ->setVolumes(['/code-docker' => (object) []])
            ->setHostConfig($hostConfig)
            ->setWorkingDir('/code-docker')
            ->setCmd(['ls', '-la'])
    );
    $docker->getContainerManager()->start($containerCreateResult->getId());

    $response = $docker->getContainerManager()->wait($containerCreateResult->getId());
    $response = $docker->getContainerManager()->find($containerCreateResult->getId());
    $response = $docker->getContainerManager()->logs($containerCreateResult->getId(), [
        'stderr' => true,
        'stdout' => true
    ]);

    dump($response);
} catch (ServerErrorException $e) {
    dump($e->getResponse()->getBody()->getContents());
    throw $e;
}
```

If I run it under my host machine, it works correctly:

```
$ php test.php 
Cannot load Xdebug - it was already loaded
array:2 [
  "stdout" => array:39 [
    0 => "total 3212\n"
    1 => "drwxr-xr-x   14 1000     1000          4096 Oct  1 09:39 .\n"
    2 => "drwxr-xr-x   19 root     root          4096 Oct  1 09:39 ..\n"
    3 => "-rw-r--r--    1 1000     1000           314 Sep 21 21:05 .babelrc\n"
    4 => "-rw-r--r--    1 1000     1000           210 Sep 21 20:33 .editorconfig\n"
    5 => "-rw-r--r--    1 1000     1000            92 Sep 22 17:00 .env\n"
    6 => "-rw-r--r--    1 1000     1000           115 Sep 22 17:00 .env.dist\n"
    7 => "-rw-r--r--    1 1000     1000          2922 Sep 21 20:51 .eslintrc.js\n"
    8 => "drwxr-xr-x    8 1000     1000          4096 Oct  1 09:39 .git\n"
    9 => "-rw-r--r--    1 1000     1000           334 Sep 28 18:27 .gitignore\n"
    10 => "-rw-r--r--    1 1000     1000           404 Sep 30 13:18 .gitlab-ci.yml\n"
    11 => "drwxr-xr-x    4 1000     1000          4096 Oct  1 09:39 .idea\n"
    12 => "-rw-r--r--    1 1000     1000          1265 Sep 22 22:15 .php_cs\n"
    13 => "-rw-r--r--    1 1000     1000          6286 Sep 30 23:30 .php_cs.cache\n"
    14 => "-rw-r--r--    1 1000     1000           442 Sep 22 22:17 Makefile\n"
    15 => "-rw-rw-r--    1 1000     1000           329 Sep 21 21:59 README.md\n"
    16 => "drwxr-xr-x    5 1000     1000          4096 Sep 30 13:18 app\n"
    17 => "drwxr-xr-x    5 1000     1000          4096 Sep 22 17:00 assets\n"
    18 => "drwxr-xr-x    2 1000     1000          4096 Sep 30 13:34 bin\n"
    19 => "-rw-r--r--    1 1000     1000          2608 Sep 30 13:34 composer.json\n"
    20 => "-rw-r--r--    1 1000     1000        184455 Sep 30 13:34 composer.lock\n"
    21 => "-rwxr-xr-x    1 1000     1000           209 Sep 22 17:00 configure\n"
    22 => "drwxr-xr-x    5 1000     1000          4096 Sep 22 17:00 docker\n"
    23 => "-rw-r--r--    1 1000     1000           133 Sep 28 18:09 docker-compose.override.yml\n"
    24 => "-rw-r--r--    1 1000     1000           136 Sep 28 18:27 docker-compose.override.yml.dist\n"
    25 => "-rw-r--r--    1 1000     1000          1195 Sep 30 23:29 docker-compose.yml\n"
    26 => "-rwxr-xr-x    1 1000     1000           161 Sep 22 17:00 docker-console\n"
    27 => "drwxr-xr-x  760 1000     1000         32768 Sep 22 17:03 node_modules\n"
    28 => "-rw-r--r--    1 1000     1000           543 Sep 22 17:00 package.json\n"
    29 => "-rw-r--r--    1 1000     1000       2724060 Aug  4 05:26 phpunit-6.3.phar\n"
    30 => "-rw-r--r--    1 1000     1000           749 Sep 21 19:52 phpunit.xml.dist\n"
    31 => "drwxr-xr-x    3 1000     1000          4096 Sep 21 19:48 src\n"
    32 => "-rw-r--r--    1 1000     1000          1249 Oct  1 09:39 test.php\n"
    33 => "drwxr-xr-x    2 1000     1000          4096 Sep 22 17:22 tests\n"
    34 => "drwxr-xr-x    5 1000     1000          4096 Sep 21 20:05 var\n"
    35 => "drwxr-xr-x   37 1000     1000          4096 Sep 30 13:34 vendor\n"
    36 => "drwxr-xr-x    4 1000     1000          4096 Sep 30 13:34 web\n"
    37 => "-rw-r--r--    1 1000     1000          1000 Sep 22 17:00 webpack.config.js\n"
    38 => "-rw-r--r--    1 1000     1000        190286 Sep 22 17:00 yarn.lock\n"
  ]
  "stderr" => []
]
```

But not onto my docker console instance, which I want to get it working:

```
$ ./docker-console 
sullivan@93d0cb373e1c:/code$ php test.php 
array:2 [
  "stdout" => array:2 [
    0 => ".:\n"
    1 => "total 0\n"
  ]
  "stderr" => []
]
```

I tried with the `pwd` command, I have the same path result.

Here is my `docker-compose.yml` file:

```yaml
version: '2'

services:
  data:
    image: alpine
    volumes:
      - .:/code

  apache:
    build: docker/php-apache
    links:
      - mysql
      - rabbitmq
    ports:
      - '${PORTS_FIRST_NUMBER}000:80'
    volumes_from:
      - data
    volumes:
      - ./docker/conf/apache_vhost.conf:/etc/apache2/sites-enabled/default.conf:ro
    env_file:
      - .env

  console:
    build: docker/php-console
    volumes_from:
      - data
    depends_on:
      - apache
      - mysql
      - rabbitmq
      - docker
    env_file:
      - .env
    environment:
      - DOCKER_HOST=tcp://docker:2375

  mysql:
    image: mysql:5.7
    volumes_from:
      - data
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - '${PORTS_FIRST_NUMBER}200:15672'

  docker:
    image: docker:17-dind
    privileged: true

  ngrok:
    image: wernight/ngrok
    ports:
      - '${PORTS_FIRST_NUMBER}040:4040'
    links:
      - apache
    environment:
      NGROK_PORT: apache:80

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - '${PORTS_FIRST_NUMBER}100:80'
    environment:
      - PMA_USER=root
```

My console `Dockerfile`:

```
FROM nexylan/php-dev:7.1

COPY entrypoint.sh /
RUN chmod u+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

WORKDIR /code

CMD ["tail", "--follow", "--lines=0", "/var/log/dmesg"]
```

And the entrypoint of this container:

```bash
#!/usr/bin/env bash
set -e

setup

# Wait for composer vendor
if [ ! -f vendor/autoload.php ]; then
    echo "Run 'composer install' command to continue."
fi
while [ ! -f vendor/autoload.php ]; do
    sleep 1
done
echo "Composer vendor found, processing."

# Wait for application cache
if [ ! -f var/cache/dev/appDevDebugProjectContainer.php ]; then
    echo "Run './bin/console cache:warmup' command to continue."
fi
while [ ! -f var/cache/dev/appDevDebugProjectContainer.php ]; do
    sleep 1
done
echo "Application cache found, processing."

exec "$@"
```

Am I missing something? Anybody having the same issue?

**Comment by Soullivaneuh** [comment]
I finally found a way to solve it:

```yaml
  docker:
    image: docker:17-dind
    volumes_from:
      - data
    privileged: true
```

With `volumes_from`, the docker image has now the same volume as my console, and it is now working.

Not sure it's the best option, but it is working this way.
