### ISSUE TITLE
x-nullable: true ignored for EndpointSettingsNormalizer.php IPAMConfig

### ISSUE THREAD

**Issue by Rid** [docker-php/docker-php#275]
The swagger file for 1.33 has:

```yaml
EndpointIPAMConfig:
    description: |
      EndpointIPAMConfig represents an endpoint's IPAM configuration.
    type: "object"
    x-nullable: true
    properties:
      IPv4Address:
        type: "string"
        example: "172.20.30.33"
      IPv6Address:
        type: "string"
        example: "2001:db8:abcd::3033"
      LinkLocalIPs:
        type: "array"
        items:
          type: "string"
        example:
          - "169.254.34.68"
          - "fe80::3468"
```

However, in the code there's no protection against this being null (a valid case) which causes the following error:

`PHP Fatal error:  Uncaught Symfony\Component\Serializer\Exception\InvalidArgumentException in /vendor/docker-php/docker-php/generated/1.33/Normalizer/EndpointIPAMConfigNormalizer.php:45`

Perhaps the generator upon `x-nullable` should change

```php
if (property_exists($data, 'IPAMConfig') && !is_object($data->{'IPAMConfig'})) {
    $object->setIPAMConfig($this->denormalizer->denormalize($data->{'IPAMConfig'}, 'Docker\\API\\V1_33\\Model\\EndpointIPAMConfig', 'json', $context));
}
```

to

```php
if (property_exists($data, 'IPAMConfig')) {
    if (is_object($data->{'IPAMConfig'})) {
        $object->setIPAMConfig($this->denormalizer->denormalize($data->{'IPAMConfig'}, 'Docker\\API\\V1_33\\Model\\EndpointIPAMConfig', 'json', $context));
    }
}
```
