### ISSUE TITLE
"Invalid argument supplied for foreach()" in case container does not have mapped all the ports

### ISSUE THREAD

**Issue by Delorien84** [docker-php/docker-php#308]
Hi,
 when calling `Client::containerInspect` on container that does not have mapped all ports, I get `Invalid argument supplied for foreach()` exception in `Normalizer/NetworkSettingsNormalizer.php:60`.

The `$value` variable may be null in case the port is not mapped

```
        if (property_exists($data, 'Ports') && $data->{'Ports'} !== null) {
            $values = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
            foreach ($data->{'Ports'} as $key => $value) {
                $values_1 = [];
                foreach ($value as $value_1) {
                    $values_1[] = $this->denormalizer->denormalize($value_1, 'Docker\\API\\Model\\PortBinding', 'json', $context);
                }
                $values[$key] = $values_1;
            }
            $object->setPorts($values);
        }

```

Fragment of docker inspect command:

```
               "8302/udp": null,
                "8500/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32792"
                    }
                ],
```

**Comment by NuBOXDevCom** [comment]
See https://github.com/NuBOXDevCom/docker-php-api/commit/f490742003c5c0d6f457eaa0c1f95e297cfcc744 
for fix issue temporarily ;)

**Comment by GroovyCarrot** [comment]
Looks like Jane doesn't generate the logic correctly based on `x-nullable: true`
```yaml
  PortBinding:
    description: |
      PortBinding represents a binding between a host IP address and a host
      port.
    type: "object"
    x-nullable: true
    properties:
      HostIp:
        description: "Host IP address that the container's port is mapped to."
        type: "string"
        example: "127.0.0.1"
      HostPort:
        description: "Host port number that the container's port is mapped to."
        type: "string"
        example: "4443"
```
